
name: testing secrets
on:
  push:
    branches: main

jobs:
  testing:
    runs-on: arc-runners-default
    defaults:
      run:
        shell: bash
    steps:
        - name: Expose github environment as shell variables
          env:
            SECRETS_CONTEXT: ${{ toJson(secrets) }}
          run: |
            # https://docs.github.com/en/actions/using-workflows/workflow-commands-for-github-actions#setting-an-environment-variable
            # https://docs.github.com/en/actions/using-workflows/workflow-commands-for-github-actions#multiline-strings
            EOF=$(dd if=/dev/urandom bs=15 count=1 status=none | base64)
            to_envs() { jq -r "to_entries[] | \"\(.key)<<$EOF\n\(.value)\n$EOF\n\""; }
            echo "$SECRETS_CONTEXT" | to_envs >> $GITHUB_ENV
