
name: testing secrets
on:
  push:
    branches: main

jobs:
  testing:
    runs-on: ubuntu-slim
    defaults:
      run:
        shell: bash
    steps:
        - name: Expose github environment as shell variables
          env:
            SECRETS_CONTEXT: ${{ toJson(secrets) }}
          run: |
            MANIFESTO=$(jq -n -c '
            env.SECRETS_CONTEXT | fromjson | 
            {
              "apiVersion": "v1",
              "kind": "Secret",
              "metadata": {
                "name": env.SECRET_NAME,
                "namespace": env.NAMESPACE
              },
              "type": "Opaque",
              "data": (
                to_entries | 
                # 1. Filtra segredos do sistema (GitHub/Azure)
                map(select(.key | test("github|azure"; "i") | not)) |
                # 2. Garante que a KEY seja válida para o K8s (remove se tiver asterisco do log)
                map(select(.key | test("^[-._a-zA-Z][-._a-zA-Z0-9]*$"))) |
                # 3. Remove valores nulos ou vazios
                map(select(.value != null and .value != "")) |
                # 4. Converte o valor para Base64
                map({key: .key, value: (.value | tostring | @base64)}) | 
                from_entries
              )
            }
            ')

            # Verifica se o manifesto gerado contém dados antes de aplicar
            if [ "$(echo "$MANIFESTO" | jq ".data | length")" -eq 0 ]; then
              echo "Aviso: Nenhum segredo válido encontrado para processar."
            else
              echo $MANIFESTO
            fi
